wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.12
    start_time: 1728295816.576049
    t:
      1:
      - 55
      3:
      - 13
      - 23
      4: 3.10.12
      5: 0.13.5
      8:
      - 5
